# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0003_remove_movie_moveieid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='moveieID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
