# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0005_auto_20170727_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='users',
        ),
    ]
